server:
  port: 8081
  context-path: /manager/
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/manager?user=root&password=root&useUnicode=true&characterEncoding=utf-8
  jpa:
    show-sql: true
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
